AdminPanel/FinalExamRea/Controllers/NoteController.cs
using FinalExamRea.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace AdminBlog.Controllers
{
    public class NoteController : Controller
    {
        private readonly ILogger<NoteController> _logger;
        private readonly NoteContext _context;

        public NoteController(ILogger<NoteController> logger, NoteContext context)
        {
            _logger = logger;
            _context = context;
        }
        public IActionResult Index()
        {
            ViewBag.Categories = _context.Categories.Select(w =>
            new SelectListItem
            {
                Text = w.Name,
                Value = w.Id.ToString()
            }
            ).ToList();
            var list = _context.Notes.ToList();

            return View(list);

        }
        public IActionResult Publish(int Id)
        {
            var note = _context.Notes.Find(Id);
            note.IsPublish = true;
            _context.Update(note);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Note()
        {
            ViewBag.Categories = _context.Categories.Select(w =>
            new SelectListItem
            {
                Text = w.Name,
                Value = w.Id.ToString()
            }
            ).ToList();
            ViewBag.Tags = _context.Tags.Select(w =>
            new SelectListItem
            {
                Text = w.Name,
                Value = w.Id.ToString()
            }
            ).ToList();
            return View();

        }
        public IActionResult UpdateNote(int? id)
        {
            var note = _context.Notes.Find(id);
            ViewBag.Categories = _context.Categories.Select(w =>
            new SelectListItem
            {
                Text = w.Name,
                Value = w.Id.ToString()
            }
            ).ToList();
            ViewBag.Tags = _context.Tags.Select(w =>
            new SelectListItem
            {
                Text = w.Name,
                Value = w.Id.ToString()
            }
            ).ToList();
            ViewBag.Note = note;
            return View();

        }

        public  IActionResult DeleteNote(int? id)
        {
            var note = _context.Notes.Find(id);
            _context.Remove(note);
            _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Save(Note model)
        {
            if (model != null)
            {
                model.AuthorId = (int)HttpContext.Session.GetInt32("id");
                await _context.AddAsync(model);
                await _context.SaveChangesAsync();
                return Json(true);
            }
            return Json(false);
        }
        public async Task<IActionResult> Update(Note model)
        {
            if (model != null)
            {
                model.AuthorId = (int)HttpContext.Session.GetInt32("id");
                _context.Update(model);
                await _context.SaveChangesAsync();
                return Json(true);
            }
            return Json(false);
        }

    }
}

AdminPanel/FinalExamRea/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
@{
    int? id = Context.Session.GetInt32("id");
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FinalExamRea</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
        <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
</head>
<body>
     @if (id.HasValue)
    {
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FinalExamRea</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                         @if (!id.HasValue)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Category">Home</a>
                                </li>
                            }
                            <li class="nav-item">
                            <a class="nav-link text-dark"  asp-area="" asp-controller="Home" asp-action="Category">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Tag">Tag</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Author">Author</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Note" asp-action="Index">Note</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    }
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - FinalExamRea - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>